# Generated by Django 3.2.8 on 2021-12-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.ImageField(blank=True, upload_to='assets')),
                ('video', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.ImageField(blank=True, upload_to='assets')),
                ('video', models.URLField(blank=True)),
                ('survey_question', models.TextField(blank=True, null=True)),
                ('estimated_time', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('media', models.ImageField(blank=True, upload_to='assets')),
                ('email', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='assets')),
                ('survey_question', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quests', to='journeys.submittedjourney')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyQuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.journey')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.quest')),
            ],
            options={
                'db_table': 'journeys_journey_quests',
                'ordering': ['order'],
                'unique_together': {('journey', 'quest', 'order')},
            },
        ),
        migrations.AddField(
            model_name='journey',
            name='quests',
            field=models.ManyToManyField(related_name='quests', through='journeys.JourneyQuests', to='journeys.Quest'),
        ),
    ]
